services:
  backend:
    build:
      target: "${BACKEND_TARGET:-final}"
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app:rw 
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: user
      DB_PASSWORD: secret
      DB_DATABASE: avenue

  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user
      POSTGRES_DB: avenue
    ports:
      - "5432:5432"
   
